# © Joseph Cameron - All Rights Reserved

cmake_minimum_required(VERSION 3.21 FATAL_ERROR)

include("${CMAKE_CURRENT_SOURCE_DIR}/cmake/jfc-cmake/jfclib.cmake")

project(gdkgraphics_data
    VERSION 0.9
    DESCRIPTION "game development kit graphics data lib")

option(JFC_BUILD_DOCS "Build documentation" OFF)
option(JFC_BUILD_TESTS "Build unit tests" OFF)

set(_jfc_outer_build_tests "${JFC_BUILD_TESTS}")
set(_jfc_outer_build_docs "${JFC_BUILD_DOCS}")
set(_jfc_outer_build_bench "${JFC_BUILD_BENCH}")

set(JFC_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(JFC_BUILD_DOCS OFF CACHE BOOL "" FORCE)
set(JFC_BUILD_BENCH OFF CACHE BOOL "" FORCE)

include("${CMAKE_CURRENT_SOURCE_DIR}/extern/stb.cmake")
include("${CMAKE_CURRENT_SOURCE_DIR}/extern/cgltf.cmake")

add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/extern/gdk-math")

set(JFC_BUILD_TESTS "${_jfc_outer_build_tests}" CACHE BOOL "" FORCE)
set(JFC_BUILD_DOCS "${_jfc_outer_build_docs}" CACHE BOOL "" FORCE)
set(JFC_BUILD_BENCH "${_jfc_outer_build_bench}" CACHE BOOL "" FORCE)

set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

if (MSVC)
    add_compile_options($<$<COMPILE_LANGUAGE:CXX>:/permissive->)
else()
    if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-pedantic>)
    endif()

    include(CheckCXXCompilerFlag)

    foreach (_strict_flag "-Werror=c++20-extensions" "-Werror=c++23-extensions")
        string(MAKE_C_IDENTIFIER "HAS${_strict_flag}" _strict_flag_symbol)

        check_cxx_compiler_flag("${_strict_flag}" ${_strict_flag_symbol})

        if (${_strict_flag_symbol})
            add_compile_options($<$<COMPILE_LANGUAGE:CXX>:${_strict_flag}>)
        endif()
    endforeach()
endif()

add_library(gdkgraphics_data STATIC
    ${CMAKE_CURRENT_SOURCE_DIR}/src/attribute_data.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/color.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/model_data.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ext/animation/bvh.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ext/animation/ik.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ext/animation/profile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ext/animation/retarget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ext/animation/skeleton.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ext/animation/skinning.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ext/aseprite.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ext/font.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ext/gltf.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ext/png.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ext/sprite_animation.cpp)

add_library(gdk::graphics_data ALIAS gdkgraphics_data)

set_target_properties(gdkgraphics_data PROPERTIES EXPORT_NAME graphics_data)

set_target_properties(gdkgraphics_data PROPERTIES PREFIX "lib")

target_include_directories(gdkgraphics_data
    PUBLIC
        "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>"
        "$<INSTALL_INTERFACE:include>")

target_compile_features(gdkgraphics_data PUBLIC cxx_std_20)

target_link_libraries(gdkgraphics_data
    PUBLIC
        gdkmath
    PRIVATE
        stb
        cgltf)

if (JFC_BUILD_TESTS)
    add_subdirectory(test)
endif()

if (JFC_BUILD_FUZZERS)
    add_subdirectory(fuzz)
endif()

